going to original

diff --git a/.github/workflows/time-tracker-ui-ci.yml b/.github/workflows/time-tracker-ui-ci.yml
--- a/.github/workflows/time-tracker-ui-ci.yml
+++ b/.github/workflows/time-tracker-ui-ci.yml
@@ -5,9 +5,9 @@ on:
     branches:
     - "**"
 
-  # pull_request:
-  #   branches:
-  #   - "**"
+  pull_request:
+    branches:
+    - "**"
 
 jobs:
   ci:
@@ -45,14 +45,14 @@ jobs:
         ./append_secret.py AZURE_APP_CONFIGURATION_CONNECTION_STRING "${{ secrets.AZURE_APP_CONFIGURATION_CONNECTION_STRING }}"
 
 
-    # - name: Running tests
-    #   run: |
-    #     chmod -R 777 ./$home
-    #     make test
-    # - name: Generate coverage report
-    #   env:
-    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-    #   run: bash <(curl -s https://codecov.io/bash)
+    - name: Running tests
+      run: |
+        chmod -R 777 ./$home
+        make test
+    - name: Generate coverage report
+      env:
+        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+      run: bash <(curl -s https://codecov.io/bash)
 
     - name: Setup terraform
       uses: hashicorp/setup-terraform@v1
@@ -71,8 +71,7 @@ jobs:
 
     - name: Terraform Plan Stage
       id: plan-stage
-      run: | 
-        terraform plan -var-file=${{ env.TF_WORKSPACE }}.tfvars  -var image_tag=latest  -no-color
+      run: terraform plan -var-file=${{ env.TF_WORKSPACE }}.tfvars  -var image_tag=latest  -no-color
       continue-on-error: true
       working-directory: ./${{ env.WORKING_DIR }}
       env:
@@ -120,32 +119,32 @@ jobs:
             body: output
           })
 
-    - name: Update Pull Request with Prod Plan
-      uses: actions/github-script@0.9.0
-      if: github.event_name == 'pull_request'
-      env:
-        PLAN: "terraform\n${{ steps.plan-prod.outputs.stdout }}"
-        TF_WORKSPACE: prod
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          const output = `#### [${{ env.WORKING_DIR }}][${{ env.TF_WORKSPACE }}] Terraform Plan 📖 \`${{ steps.plan-prod.outcome }}\`
-          <details><summary>Show Plan</summary>
-          \`\`\`\n
-          ${process.env.PLAN}
-          \`\`\`
-          </details>
-          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-          github.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
+    # - name: Update Pull Request with Prod Plan
+    #   uses: actions/github-script@0.9.0
+    #   if: github.event_name == 'pull_request'
+    #   env:
+    #     PLAN: "terraform\n${{ steps.plan-prod.outputs.stdout }}"
+    #     TF_WORKSPACE: prod
+    #   with:
+    #     github-token: ${{ secrets.GITHUB_TOKEN }}
+    #     script: |
+    #       const output = `#### [${{ env.WORKING_DIR }}][${{ env.TF_WORKSPACE }}] Terraform Plan 📖 \`${{ steps.plan-prod.outcome }}\`
+    #       <details><summary>Show Plan</summary>
+    #       \`\`\`\n
+    #       ${process.env.PLAN}
+    #       \`\`\`
+    #       </details>
+    #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+    #       github.issues.createComment({
+    #         issue_number: context.issue.number,
+    #         owner: context.repo.owner,
+    #         repo: context.repo.repo,
+    #         body: output
+    #       })
     - name: Terraform Plan Stage Status
       if: steps.plan-stage.outcome == 'failure'
       run: exit 1
 
-    - name: Terraform Plan Prod Status
-      if: steps.plan-prod.outcome == 'failure'
-      run: exit 1
+    # - name: Terraform Plan Prod Status
+    #   if: steps.plan-prod.outcome == 'failure'
+    #   run: exit 1
